name: CI
on:
  push:
    branches: [main]
jobs:
  behave-test-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run test & generate report
        run: |
          pip install -r behave/requirements.txt
          behave behave/features -f json -o reports/behave-report.json
      - name: Upload report to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: behave-report
          path: reports/
      - name: Upload report to AgileTest.App
        run: |
          docker run --rm \
          -e AGILETEST_BASE_URL=${{ secrets.AGILETEST_BASE_URL }} \
          -e AGILETEST_AUTH_BASE_URL=${{ secrets.AGILETEST_AUTH_BASE_URL }} \
          -e AGILETEST_CLIENT_ID=${{ secrets.AGILETEST_CLIENT_ID }} \
          -e AGILETEST_CLIENT_SECRET=${{ secrets.AGILETEST_CLIENT_SECRET }} \
          ghcr.io/agiletestapp/agiletest-cli:latest \
          test-execution import --framework-type behave --project-key TC \
          <reports/behave-report.json
